### ISSUE TITLE
plot_uv fails when using 10 time steps and 1 integration step.

### ISSUE THREAD

**Issue by chrisfinlay** [chrisfinlay/tabascal#4]
Running `sim-calib --N_t 10 --N_int 1` leads to the following error:

```
Traceback (most recent call last):
  File "/nfs/chris/projects/tab_dev/tabascal/tabascal/examples/calibration_observation.py", line 199, in <module>
    main()
  File "/nfs/chris/projects/tab_dev/tabascal/tabascal/examples/calibration_observation.py", line 176, in main
    plot_uv(obs, save_path)
  File "/nfs/chris/projects/tab_dev/tabascal/tabascal/utils/plot.py", line 103, in plot_uv
    u = obs.bl_uvw[::time_step,:,0].compute().flatten()
        ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/nfs/chris/micromamba/envs/tab/lib/python3.12/site-packages/dask/array/core.py", line 1978, in __getitem__
    index2 = normalize_index(index, self.shape)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/chris/micromamba/envs/tab/lib/python3.12/site-packages/dask/array/slicing.py", line 822, in normalize_index
    idx = tuple(map(normalize_slice, idx, none_shape))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/chris/micromamba/envs/tab/lib/python3.12/site-packages/dask/array/slicing.py", line 739, in normalize_slice
    start, stop, step = idx.indices(dim)
                        ^^^^^^^^^^^^^^^^
ValueError: slice step cannot be zero
```

**Comment by chrisfinlay** [comment]
Fixed by pull request #5.
